"""Generate the ExtendScript that the MCP bridge panel evaluates."""
from pathlib import Path

from .ops import validate_ops
from .util import js

RUNTIME = Path(__file__).resolve().parents[1] / "jsx" / "runtime.jsx"


def emit_script(ops, project=None, folder="ae-video-studio", runtime=RUNTIME) -> str:
    validate_ops(ops)
    spec = {"folder": folder, "project": project}
    return "\n".join([
        "// generated by ae-video-studio; rebuild instead of editing",
        f"$.evalFile(new File({js(str(runtime))}));",
        f"AES.build({js(spec)},{js(ops)});",
    ])


def still_script(comp: str, time: float, out_png: str) -> str:
    return ("(function(){var c=null;for(var i=1;i<=app.project.numItems;i++){var it=app.project.item(i);"
            "if(it instanceof CompItem&&it.name===" + js(comp) + ")c=it;}"
            "if(!c){return '{\"ok\":false,\"error\":\"comp not found\"}';}"
            "var f=new File(" + js(out_png) + ");if(f.exists){f.remove();}"
            "c.saveFrameToPng(" + repr(float(time)) + ",f);return '{\"ok\":true}';})();")
