"""Generate the ExtendScript that the MCP bridge panel evaluates."""
import unicodedata
from pathlib import Path

from .ops import validate_ops
from .util import js

RUNTIME = Path(__file__).resolve().parents[1] / "jsx" / "runtime.jsx"


def nfc(value):
    """macOS reports filesystem paths as NFD; After Effects reports them as NFC.

    A path containing non-ASCII characters (Korean, accents) therefore fails the
    "is this the same project?" comparison in runtime.jsx even when both spellings
    point at the same file. Normalise every path we emit so the two forms agree.
    """
    return unicodedata.normalize("NFC", value) if isinstance(value, str) else value


def _nfc_paths(ops):
    return [dict(o, file=nfc(o["file"])) if isinstance(o, dict) and isinstance(o.get("file"), str) else o
            for o in ops]


def emit_script(ops, project=None, folder="ae-video-studio", runtime=RUNTIME) -> str:
    validate_ops(ops)
    ops = _nfc_paths(ops)
    spec = {"folder": folder, "project": nfc(project)}
    return "\n".join([
        "// generated by ae-video-studio; rebuild instead of editing",
        f"$.evalFile(new File({js(str(runtime))}));",
        f"AES.build({js(spec)},{js(ops)});",
    ])


def still_script(comp: str, time: float, out_png: str) -> str:
    return ("(function(){var c=null;for(var i=1;i<=app.project.numItems;i++){var it=app.project.item(i);"
            "if(it instanceof CompItem&&it.name===" + js(comp) + ")c=it;}"
            "if(!c){return '{\"ok\":false,\"error\":\"comp not found\"}';}"
            "var f=new File(" + js(out_png) + ");if(f.exists){f.remove();}"
            "c.saveFrameToPng(" + repr(float(time)) + ",f);return '{\"ok\":true}';})();")
