import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from aestudio.jsx import RUNTIME, emit_script, still_script
from aestudio.ops import OpsError

OPS = [{"op": "comp", "name": "DEMO", "width": 3840, "height": 2160, "fps": 23.976, "duration": 5},
       {"op": "text", "id": "T", "text": "가", "font": "F", "size": 10, "color": [0, 0, 0]}]


class JsxTest(unittest.TestCase):
    def test_emit_script_loads_runtime_and_builds(self):
        code = emit_script(OPS, project="/tmp/p.aep")
        lines = code.splitlines()
        self.assertTrue(lines[0].startswith("// generated by ae-video-studio"))
        self.assertIn(str(RUNTIME), lines[1])
        self.assertTrue(lines[1].startswith("$.evalFile(new File("))
        self.assertTrue(lines[2].startswith('AES.build({"folder":"ae-video-studio","project":"/tmp/p.aep"},[{"op":"comp"'))
        self.assertIn("\\uac00", lines[2])

    def test_emit_script_validates(self):
        with self.assertRaises(OpsError):
            emit_script([{"op": "group", "id": "G"}])

    def test_still_script(self):
        code = still_script("DEMO", 3.5, "/tmp/a.png")
        self.assertIn('it.name==="DEMO"', code)
        self.assertIn('c.saveFrameToPng(3.5,f)', code)
        self.assertIn('new File("/tmp/a.png")', code)

    def test_runtime_exists_and_defines_all_ops(self):
        src = RUNTIME.read_text(encoding="utf-8")
        from aestudio.ops import REQUIRED
        for op in REQUIRED:
            self.assertRegex(src, r"\n\s+%s: function \(o\)" % op, op)

    @unittest.skipUnless(shutil.which("node"), "node not installed")
    def test_runtime_is_syntactically_valid(self):
        # node only checks .js files, so check a copy; ES3 ExtendScript is valid JavaScript syntax
        with tempfile.TemporaryDirectory() as d:
            copy = Path(d) / "runtime.js"
            copy.write_text(RUNTIME.read_text(encoding="utf-8"), encoding="utf-8")
            r = subprocess.run(["node", "--check", str(copy)], capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, r.stderr)


if __name__ == "__main__":
    unittest.main()
